# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote_calls/game.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17remote_calls/game.proto\"-\n\x0cPlayerChoice\x12\x0e\n\x06square\x18\x01 \x01(\t\x12\r\n\x05piece\x18\x02 \x01(\x05\"\x18\n\x05Reply\x12\x0f\n\x07message\x18\x01 \x01(\t26\n\x0bPiecePlacer\x12\'\n\x0c\x43hooseSquare\x12\r.PlayerChoice\x1a\x06.Reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'remote_calls.game_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PLAYERCHOICE']._serialized_start=27
  _globals['_PLAYERCHOICE']._serialized_end=72
  _globals['_REPLY']._serialized_start=74
  _globals['_REPLY']._serialized_end=98
  _globals['_PIECEPLACER']._serialized_start=100
  _globals['_PIECEPLACER']._serialized_end=154
# @@protoc_insertion_point(module_scope)
