# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote_calls/game.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17remote_calls/game.proto\"5\n\x0cPlayerChoice\x12\x0e\n\x06square\x18\x01 \x01(\t\x12\x15\n\x05piece\x18\x02 \x01(\x0e\x32\x06.Piece\"\x18\n\x05Reply\x12\x0f\n\x07message\x18\x01 \x01(\t*\x15\n\x05Piece\x12\x05\n\x01O\x10\x00\x12\x05\n\x01X\x10\x01\x32\x36\n\x0bPiecePlacer\x12\'\n\x0c\x43hooseSquare\x12\r.PlayerChoice\x1a\x06.Reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'remote_calls.game_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PIECE']._serialized_start=108
  _globals['_PIECE']._serialized_end=129
  _globals['_PLAYERCHOICE']._serialized_start=27
  _globals['_PLAYERCHOICE']._serialized_end=80
  _globals['_REPLY']._serialized_start=82
  _globals['_REPLY']._serialized_end=106
  _globals['_PIECEPLACER']._serialized_start=131
  _globals['_PIECEPLACER']._serialized_end=185
# @@protoc_insertion_point(module_scope)
